### ISSUE TITLE
p6spy should not fail transactions when it can't write to it's log

### ISSUE THREAD

**Issue by wimfabri** [p6spy/p6spy#483] opened 2019-08-07 08:45 UTC
When p6spy wants to log a query and can't write to it's log it throws an exception. This makes the query fail for the application. Before version 3.8.4 it was a nullpointerexception, in 3.8.4 the file handling exception is rethrown. A logging subsystem like p6spy should not make the application fail when it can't log.

**Comment by typekpb** [comment] 2019-08-07 14:53
What would be the behaviour you'd expect then? we're open to discussion.

**Comment by wimfabri** [comment] 2019-08-07 15:06
I would prefer the following behaviour:

Don't throw an exception and return to the application as if nothing had 
to be logged. Log a warning to stdout or stderr.


Met vriendelijke groeten,
Bien à vous,
Best regards,


*Wim Fabri
**/Senior System Engineer/*

Xenit

	

*XENIT Solutions nv* <http://www.xenit.eu/>
Diestsevest 32 bus 4A
B3000 Leuven
Belgium

Tel: +32 475 33 81 37

wim.fabri@xenit.eu <mailto:wim.fabri@xenit.eu>

**Comment by typekpb** [comment] 2019-08-07 18:35
@wimfabri: hm, the possible problem I see with the solution proposed is that you won't see any error on the app startup and once you need to find the query, you won't find any. Moreover finding the root cause might be tricky, as initial log could be already lost/gone.

I'd be rather forcing people to fix their setup if they want logging enabled. Anyway, I consider the change request you propose a breaking one. As we'd just silence the error handling we've had in place for a longer time (exception thrown:  either `NullPointerException` or original rethrown).

So I'm tempted to close this one with Won't fix label.

ideas, anyone? @gavlyukovskiy

**Comment by gavlyukovskiy** [comment] 2019-08-08 11:56
@typekpb I agree with you, that we should indicate by error if something wrong with the configuration. When I changed exception handling it was choice between NPE and rethrowing existing exception with useful information. In this case error is purely due to configuration error and should be treated just like providing incorrect class in `modulelist` - fail indicating what is wrong.

From the other hand logging libraries tend not to fail when something is wrong (can happen that we run out of disk space), but p6spy isn't a logging library and if application intends to run in such conditions I would suggest not to use `appender=com.p6spy.engine.spy.appender.FileLogger`, but `appender=com.p6spy.engine.spy.appender.Slf4JLogger` (IMO it should be the default option) and configure logging library accordingly. I think all of them have ability to write logs from specific logger, in our case `p6spy`, into separate file.

**Comment by typekpb** [comment] 2019-08-08 11:58
@gavlyukovskiy thanks for the feedback, closing this one

**Closed by typekpb** 2019-08-08 11:58 UTC
Labels: Won't fix
