### ISSUE TITLE
Question: Does p6spy work with Tomcat 9.X

### ISSUE THREAD

**Issue by kenx-max** [p6spy/p6spy#511] opened 2020-09-29 05:20 UTC
I saw here:
https://p6spy.readthedocs.io/en/latest/install.html#apache-tomcat-and-apache-tomee

That it's listed to work with:
Apache Tomcat 6.x, 7.x, 8.x and TomEE 1.6.x

And was wondering if there's any plan for p6spy to work with Tomcat 9.X?

Thanks for any help/info!

**Comment by typekpb** [comment] 2020-09-29 05:22
Docs might be outdated. Would you mind giving it a try and reporting back?

**Comment by typekpb** [comment] 2021-01-23 07:31
duplicate of: https://github.com/p6spy/p6spy/issues/508 => closing

**Closed by typekpb** 2021-01-23 07:31 UTC
Labels: Duplicate
