### ISSUE TITLE
CustomLineFormat not work on sql select value from V$parameter where lower(name)='compatible'

### ISSUE THREAD

**Issue by rocex** [p6spy/p6spy#417] opened 2017-10-23 06:54 UTC
spy.properties set as 
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime)|%(executionTime)|%(category)|connection%(connectionId)\n%(effectiveSqlSingleLine)\n%(sqlSingleLine);\n

on oracle db, when execute sql like this: select value from V$parameter where lower(name)='compatible'
com.p6spy.engine.spy.appender.CustomLineFormat will throw an java.lang.IllegalArgumentException on replaceAll(Pattern.quote(EFFECTIVE_SQL), prepared)

**Comment by typekpb** [comment] 2017-10-23 09:13
@rocex thanks for the report, any chance for full stacktrace?

**Comment by typekpb** [comment] 2017-10-23 09:22
@rocex ok, maybe even better, any chance for providing the failing test?

I've tried the following, but could not reproduce (failed on next line only):

	public class CustomLineFormatTest {

		@Test
		public void formatMessage() {
			String customLogMessageFormat = "%(currentTime)|%(executionTime)|%(category)|connection%(connectionId)\n%(effectiveSqlSingleLine)\n%(sqlSingleLine);\n";
			P6SpyOptions.getActiveInstance().setCustomLogMessageFormat(customLogMessageFormat);
			new CustomLineFormat().formatMessage(0, "123456", 1L, "INFO",
					"select value from V$parameter where lower(name)=$1",
					"select value from V$parameter where lower(name)='compatible'");
		}	
	}

**Comment by rocex** [comment] 2017-10-24 01:42
@typekpb 
This error occurred in handling EFFECTIVE_SQL, EFFECTIVE_SQL_SINGLELINE, SQL or SQL_SINGLE_LINE, and this setting is correct: customLogMessageFormat=%(currentTime)|%(executionTime)|%(category)|connection%(connectionId), but this not handling SQL.

the full stacktrace like this

java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Unknown Source)
	at java.util.regex.Matcher.replaceAll(Unknown Source)
	at java.lang.String.replaceAll(Unknown Source)
	at com.p6spy.engine.spy.appender.CustomLineFormat.formatMessage(CustomLineFormat.java:67)
	at com.p6spy.engine.spy.appender.Slf4JLogger.logSQL(Slf4JLogger.java:51)
	at com.p6spy.engine.common.P6LogQuery.doLog(P6LogQuery.java:121)
	at com.p6spy.engine.common.P6LogQuery.doLogElapsed(P6LogQuery.java:92)
	at com.p6spy.engine.common.P6LogQuery.logElapsed(P6LogQuery.java:201)
	at com.p6spy.engine.logging.LoggingEventListener.logElapsed(LoggingEventListener.java:108)
	at com.p6spy.engine.logging.LoggingEventListener.onAfterAnyExecute(LoggingEventListener.java:45)
	at com.p6spy.engine.event.SimpleJdbcEventListener.onAfterExecuteQuery(SimpleJdbcEventListener.java:137)
	at com.p6spy.engine.event.CompoundJdbcEventListener.onAfterExecuteQuery(CompoundJdbcEventListener.java:200)
	at com.p6spy.engine.wrapper.StatementWrapper.executeQuery(StatementWrapper.java:87)

I change CustomLineFormat.formatMessage(int, String, long, String, String, String) like this 
try
        {
            return customLogMessageFormat.replaceAll(Pattern.quote(CONNECTION_ID), Integer.toString(connectionId)).replaceAll(Pattern.quote(CURRENT_TIME), now)
                .replaceAll(Pattern.quote(EXECUTION_TIME), Long.toString(elapsed)).replaceAll(Pattern.quote(CATEGORY), category)
                .replaceAll(Pattern.quote(EFFECTIVE_SQL), prepared).replaceAll(Pattern.quote(EFFECTIVE_SQL_SINGLELINE), P6Util.singleLine(prepared))
                .replaceAll(Pattern.quote(SQL), sql).replaceAll(Pattern.quote(SQL_SINGLE_LINE), P6Util.singleLine(sql));
        }
        catch (Exception ex)
        {
            Logger.error(ex.getMessage(), ex);
            
            return FALLBACK_FORMATTING_STRATEGY.formatMessage(connectionId, now, elapsed, category, prepared, sql);
        }

**Comment by typekpb** [comment] 2017-10-27 19:10
@rocex I see the idea of your solution, but I hope we can find some more robust way to do the proper replacement of configured params and prevent default fallback. As user could get confused, once his/her pattern would be ignored.

Will report back, once I have an idea, or feel free to spread yours.

**Comment by typekpb** [comment] 2017-10-31 20:30
@rocex we have a fix for the problem reported. It comes with proper escaping of the 2.nd argument in: `String.replaceAll(String regex, String replacement)`, see #419

**Comment by OBreidenbach** [comment] 2017-11-01 10:34
Is there already a release date planed for 3.4.1?

**Comment by typekpb** [comment] 2017-11-01 11:24
Once we get this merged, we can release also today. Anyway it seems your
solution sounds like a confirmation for this PR. So I might be tempted to
merge it without further approval from any of the collaborators.

**Closed** 2017-11-02 08:55 UTC
Labels: Defect

**Comment by typekpb** [comment] 2017-11-02 11:10
@OBreidenbach 3.5.1 version has been released just now (3.5.0 never made it to bintray/maven central ,see: #423). If you'd wait 1 day, it should pre present in maven central as well.

**Comment by felixbarny** [comment] 2017-11-02 11:13
> If you'd wait 1 day, it should pre present in maven central as well.

Usually it takes like 10 minutes to sync to maven central. Although it might take a bit longer to update the index which means you can't find it via search.maven.org.

It seems like it's already there: http://central.maven.org/maven2/p6spy/p6spy/3.5.1/

**Comment by OBreidenbach** [comment] 2017-11-02 12:31
Thanks a lot. Version 3.5.1 is working well for me.
