### ISSUE TITLE
Add tests with a mock JDBC driver to validate that the time to scroll through a resultset is accurately captured.

### ISSUE THREAD

**Issue by quintonm** [p6spy/p6spy#296] opened 2015-05-22 14:11 UTC

**Comment by felixbarny** [comment] 2016-05-04 13:23
I think I know what the problem is I described here: https://github.com/p6spy/p6spy/issues/290#issuecomment-104336995

My [StagemonitorP6Logger](https://github.com/stagemonitor/stagemonitor/blob/5aa7095d1d66f9e1c8c04241aa6aab7cbb6e77d6/stagemonitor-jdbc/src/main/java/org/stagemonitor/jdbc/p6spy/StagemonitorP6Logger.java) is only enabled for `Category.STATEMENT` to include the time spent in `ResultSet#next`, I'll probably have to add `Category.RESULT` as well.

But then my P6Logger is called multiple times for one DB call and it is not quite convenient to aggregate the information, especially in a multi-threaded environment.

Ideally, I'd like to have a single callback which is called only once for a JDBC call which includes the time of all included actions (like executing the statement, scrolling, committing, ...), the sql, the preparedStatement (in case parameter should not be logged), and aggregated ResultSetInformation (#298) which includes the number of rows of all `ResultSet#next` calls.

**Comment by felixbarny** [comment] 2016-05-04 13:26
Another thing which is difficult is to know is what the last call of `P6Logger#logSql` for one DB call is. If I knew that, I could at leas aggregate the data myself.

**Comment by quintonm** [comment] 2016-05-04 16:48
Perhaps a solution to this issue would be to add the concept of events.  Applications extending/wrapping p6spy could register listeners for various events.  Each event would include basic information such as the connection, statement, execution time, exception( if any), etc.  This could be used to perform higher level aggregation that spans multiple events.

**Comment by typekpb** [comment] 2016-05-04 16:53
@quintonm I remember your initial event based implementation. Would love to
see it happen.

**Comment by typekpb** [comment] 2018-10-15 19:11
no volunteer provided the tests in 3 years => closing

**Closed by typekpb** 2018-10-15 19:11 UTC
Labels: Technical Issue
